---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "webecho-855663000"
    choreographyStackId: "53da0ad5-5117-4476-a468-3307e21e974a"
  name: "webecho-855663000"
  namespace: "001"
spec:
  ports:
  - name: "client"
    nodePort: 30080
    port: 8080
    targetPort: 80
  selector:
    app: "webecho-855663000"
  type: "NodePort"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    choreographyStackId: "53da0ad5-5117-4476-a468-3307e21e974a"
  name: "webecho-855663000"
  namespace: "001"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "webecho-855663000"
  template:
    metadata:
      labels:
        app: "webecho-855663000"
        choreographyStackId: "53da0ad5-5117-4476-a468-3307e21e974a"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: "In"
                values:
                - "webecho-855663000"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: "LISTEN_PORT"
          value: "80"
        image: "nginx:1.15.1"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
        name: "webecho"
        ports:
        - containerPort: 80
          name: "client"
        readinessProbe:
          httpGet:
            path: "/"
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
      terminationGracePeriodSeconds: 10
